In [2]:
import pandas as pd

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [3]:
df = pd.read_csv('/Users/rishi/plotly_scripting/figure_fridays/week_30/dataset/europe_monthly_electricity.csv')
df.head(2)

,Area,ISO 3 code,Date,Area type,Continent,Ember region,EU,OECD,G20,G7,ASEAN,Category,Subcategory,Variable,Unit,Value,YoY absolute change,YoY % change
0,Austria,AUT,2015-01-01,Country or economy,Europe,Europe,1.0,1.0,0.0,0.0,0.0,Electricity demand,Demand,Demand,TWh,7.58,NaN,NaN
1,Austria,AUT,2015-01-01,Country or economy,Europe,Europe,1.0,1.0,0.0,0.0,0.0,Electricity generation,Aggregate fuel,Clean,%,69.64,NaN,NaN

In [4]:
emissions_df = df[
        ((df['Category'].str.contains('emission', case=False, na=False)) |
         (df['Variable'].str.contains('emission', case=False, na=False))) &
        (df['Area'] == 'Austria')]

In [10]:
# To get all rows with the maximum value
max_rows = emissions_df[emissions_df['Value'] == emissions_df['Value'].max()]
max_rows

,Area,ISO 3 code,Date,Area type,Continent,Ember region,EU,OECD,G20,G7,ASEAN,Category,Subcategory,Variable,Unit,Value,YoY absolute change,YoY % change
1216,Austria,AUT,2017-01-01,Country or economy,Europe,Europe,1.0,1.0,0.0,0.0,0.0,Power sector emissions,CO2 intensity,CO2 intensity,gCO2e per kWh,266.67,NaN,NaN